[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "Poker-Bot"
version = "0.0.1"
requires-python = ">=3.10"

dependencies = [
    "numpy",
]

[tool.setuptools]
packages = ["poker", "scripts"]
